# Generated by Django 3.2.4 on 2021-07-18 19:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request_for_a_call',
            options={'verbose_name': 'заявка', 'verbose_name_plural': 'заявки'},
        ),
        migrations.AddField(
            model_name='request_for_a_call',
            name='data_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата время'),
        ),
    ]
