# Generated by Django 3.2.4 on 2021-07-21 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_auto_20210718_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=400, verbose_name='Название услуги'),
            preserve_default=False,
        ),
    ]
