# Generated by Django 3.2.4 on 2021-07-21 10:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_services_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=400, verbose_name='Краткое описание услуги'),
        ),
    ]
