# Generated by Django 3.2.4 on 2021-07-21 11:00

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_alter_services_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Краткое описание услуги'),
        ),
    ]
