# Generated by Django 3.2.4 on 2021-07-24 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_alter_services_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance_companies',
            name='expert_rating',
        ),
        migrations.AlterField(
            model_name='request_for_a_call',
            name='data_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='request_for_a_call',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='request_for_a_call',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.services', verbose_name='Тип сервиса'),
        ),
        migrations.AlterField(
            model_name='services',
            name='type_services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.type_services', verbose_name='Тип сервиса'),
        ),
    ]
