# Generated by Django 3.2.4 on 2021-07-24 05:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20210724_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_companies',
            name='expert_rating',
            field=models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('RD', 'RD'), ('D', 'D')], default=django.utils.timezone.now, max_length=50, verbose_name='Рейтинг эксперта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='type_services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.type_services'),
        ),
    ]
