# Generated by Django 3.2.4 on 2021-07-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_auto_20210724_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance_companies',
            name='MedalType',
            field=models.CharField(choices=[('Action', 'Action'), ('Horror', 'Horror'), ('Comedy', 'Comedy')], default='Action', max_length=20, verbose_name='Просто текс'),
        ),
    ]
