# Generated by Django 3.2.4 on 2021-07-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_insurance_companies_medaltype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance_companies',
            name='MedalType',
        ),
        migrations.AlterField(
            model_name='insurance_companies',
            name='expert_rating',
            field=models.CharField(choices=[('AAA', 'Aaa'), ('AA', 'Aa'), ('A', 'A'), ('BBB', 'Bbb'), ('BB', 'Bb'), ('B', 'B'), ('CCC', 'Ccc'), ('CC', 'Cc'), ('C', 'C'), ('RD', 'Rd'), ('D', 'D')], max_length=50, verbose_name='Рейтинг эксперта'),
        ),
    ]
