# Generated by Django 3.2.4 on 2021-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20210724_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance_companies',
            name='expert_rating',
            field=models.CharField(choices=[('AAA', 'AAA'), ('AA', 'AA'), ('A', 'A'), ('BBB', 'BBB'), ('BB', 'BB'), ('B', 'B'), ('CCC', 'CCC'), ('CC', 'CC'), ('C', 'C'), ('RD', 'RD'), ('D', 'D')], max_length=50, verbose_name='Рейтинг эксперта'),
        ),
    ]
