# Generated by Django 3.2.5 on 2021-08-11 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0010_alter_insurance_companies_expert_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Имя')),
                ('email', models.EmailField(max_length=400, verbose_name='Email')),
                ('comment', models.CharField(max_length=400, verbose_name='Коментарий')),
                ('date_of_creation', models.DateField(default=datetime.datetime.now, verbose_name='Дата создания компании')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.services')),
            ],
        ),
    ]
