# Generated by Django 3.2.5 on 2021-08-11 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0011_commentservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentservice',
            options={'ordering': ['-date_of_creation'], 'verbose_name': 'коментрий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterField(
            model_name='commentservice',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата создания компании'),
        ),
    ]
