services:
    db:
        build: ./
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: insurance_brother
        volumes:
             - ./:/usr/src/app/
        ports:
            - "5433:5432"